server:
  contextPath: /api
spring:
  datasource:
    url: jdbc:h2:mem:MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level: 
    level.: DEBUG
    level.org.hibernate.SQL: DEBUG
